lab5: main.cpp shopper.cpp store.cpp rrqueue.cpp timecheck.cpp move.cpp item.cpp binarytree.cpp lab5.h
	g++ -Wall main.cpp shopper.cpp store.cpp rrqueue.cpp timecheck.cpp move.cpp item.cpp binarytree.cpp -o lab5
	
clean:
	rm -f *.o
