lab5: main.cpp shopper.cpp store.cpp rrqueue.cpp timecheck.cpp move.cpp Item.cpp BinaryTree.cpp queue.cpp lab5.h
	g++ -Wall main.cpp shopper.cpp store.cpp rrqueue.cpp timecheck.cpp move.cpp Item.cpp BinaryTree.cpp queue.cpp -o lab5
	
clean:
	rm -f *.o
